import {GUIDE_STEPS,guideInfo,tutorialControl,noteTutorialAction,nextTask} from './tutorial.js?v=2.2.0';
import {REALMS,STAGES,ZONES,SECTS,TECHNIQUES,RECIPES,RESOURCE_NAMES,OFFLINE_CAP,createState,act,advance,maxHp,maxEnergy,attack,armor,power,requirements,canBreak,isBusy,validateSave,needExp,levelName,nextName,majorBreak,finished,idleRate,sectRank,rankName,expeditionSeconds,craftingPlan,techniqueCost,stationCost,canAfford,enemyStats} from './engine.js?v=2.2.0';
const KEY='wenshan-save-v1';let tab='home',artTab='alchemy',saved=true,saveBlocked=false,saveMessage='',toastTimer,lastRaw=null,guideTarget=null,guideExpanded=false,requirementsExpanded=false;
let state=createState();
const $=q=>document.querySelector(q),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>Math.floor(n).toLocaleString('zh-CN');
const duration=n=>n>=3600?`${Math.floor(n/3600)} 小时 ${Math.floor(n%3600/60)} 分`:n>=60?`${Math.floor(n/60)} 分 ${Math.ceil(n%60)} 秒`:`${Math.max(0,Math.ceil(n))} 秒`;
const short=n=>n>=100000000?(n/100000000).toFixed(1)+'亿':n>=10000?(n/10000).toFixed(1)+'万':fmt(n);
const percent=(a,b)=>Math.min(100,Math.max(0,a/b*100));
const missingCost=c=>Object.entries(c).filter(([k,n])=>state[k]<n).map(([k,n])=>`${fmt(n-state[k])} ${RESOURCE_NAMES[k]??k}`).join('、');
const costText=c=>Object.entries(c).filter(([k,n])=>n).map(([k,n])=>`${fmt(n)} ${RESOURCE_NAMES[k]??k}`).join(' · ');
function applyElapsed(now=Date.now(),reportOffline=false){const r=advance(state,now);if(reportOffline&&r.elapsed>=60){state.offlineReport=r;logOffline(r);}return r;}
function logOffline(r){if(r.exp||r.rounds||r.crafted)state.history.unshift({day:state.day,kind:'gain',text:`【归来】结算 ${duration(r.credited)}，修为 +${fmt(r.exp)}，巡山 ${r.rounds} 趟。${r.capped?'超过 8 小时的部分不计收益。':''}`});state.history=state.history.slice(0,80);}
try{const raw=localStorage.getItem(KEY);if(raw){let data=null;try{data=JSON.parse(raw);}catch{}let parsed=validateSave(data);if(!parsed){try{parsed=validateSave(JSON.parse(localStorage.getItem(KEY+'-last-good')));}catch{}if(parsed)saveMessage='已从上一份完整本机备份恢复进度。';else{saveBlocked=true;saveMessage='原存档暂时无法读取，已保留原数据。请勿清除网站数据；当前页面不会覆盖原存档。';}}if(parsed){if(data?.version===1&&!localStorage.getItem(KEY+'-v1-backup'))localStorage.setItem(KEY+'-v1-backup',raw);state=parsed;lastRaw=raw;applyElapsed(Date.now(),true);if(data?.version===1)saveMessage='旧存档已接续：境界、行囊和道号都还在。';}}}catch{saved=false;saveBlocked=true;saveMessage='浏览器存储不可用。原数据未被覆盖，请勿清除网站数据。';}
function save(){if(saveBlocked){saved=false;}else try{if(lastRaw){let prev;try{prev=validateSave(JSON.parse(lastRaw));}catch{}if(prev)localStorage.setItem(KEY+'-last-good',lastRaw);}state.revision++;const raw=JSON.stringify(state);localStorage.setItem(KEY,raw);lastRaw=raw;saved=true;}catch{saved=false;}$('#save-open').textContent=saved?'本机存档':'存档提示';$('#save-note').textContent=saved?'已自动保存 · 本机保留上一份完整备份':'暂未保存。请保留此页面，不要清除网站数据。';}
function syncFromStorage(){try{const raw=localStorage.getItem(KEY);if(raw&&raw!==lastRaw){const data=validateSave(JSON.parse(raw));if(data&&(data.runId!==state.runId||data.revision>state.revision)){state=data;lastRaw=raw;}}}catch{}}
function withSaveLock(fn){if(navigator.locks?.request)return navigator.locks.request(KEY,fn);return Promise.resolve(fn());}
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
async function resultAction(type,payload={}){return withSaveLock(()=>{if(saveBlocked){toast(saveMessage);return {ok:false,text:saveMessage};}syncFromStorage();applyElapsed();const guideWasDone=state.tutorial.status==='active'?guideInfo(state).done:true;const r=act(state,type,payload);if(r.ok)noteTutorialAction(state,type);save();render();if(r.ok){if(type==='breakthrough')toast(`破境成功 · ${levelName(state)}`);else if(!['explore','choice','challenge','dismissOffline'].includes(type))toast(r.text.length>90?'已完成，详情记入手记。':r.text);}else toast(r.text);return r;});}
function vitals(mobile=false){return `<div class="${mobile?'mobile-vitals':''}"><div><div class="stat-line"><span>气血</span><b>${state.hp} / ${maxHp(state)}</b></div><div class="bar hp" role="progressbar" aria-label="气血" aria-valuemin="0" aria-valuemax="${maxHp(state)}" aria-valuenow="${state.hp}"><i style="width:${percent(state.hp,maxHp(state))}%"></i></div></div><div><div class="stat-line"><span>精力 · 每 45 秒 +1</span><b>${state.energy} / ${maxEnergy(state)}</b></div><div class="bar energy"><i style="width:${percent(state.energy,maxEnergy(state))}%"></i></div></div></div>`;}
function profile(){return `<section class="profile"><div class="profile-heading"><div><div class="player-name">${esc(state.name)}</div><div class="player-sub">${state.sect?SECTS.find(s=>s.id===state.sect).name+' · '+rankName(state):'散修'}</div></div><span class="realm">${REALMS[state.realm].name}<small>${state.realm?STAGES[state.stage]:''}</small></span></div>${vitals()}<div class="stat-line"><span>修为</span><b>${short(state.exp)} / ${short(needExp(state))}</b></div><div class="bar"><i style="width:${percent(state.exp,needExp(state))}%"></i></div><div class="stats-pair"><span>攻伐<b>${attack(state)}</b></span><span>护体<b>${armor(state)}</b></span></div></section>`;}
function goal(){const missing=requirements(state).filter(r=>r.value<r.need),ready=canBreak(state);const source={'修为':'自动修炼 / 凝神','道悟':'凝神 / 历练 / 每5分钟','灵髓':'巡山 / 守关 / 坊市','灵石':'巡山 / 历练','破境丹':'炼丹'};return `<div class="goal"><div class="upgrade-row"><span class="row-label">境界</span><strong>${levelName(state)}</strong><button class="primary breakthrough-button" data-action="breakthrough" ${!ready?'disabled':''}>${finished(state)?'已圆满':'突破'}</button></div><div class="next-realm-row"><span>下一境界：${finished(state)?'已修至真仙圆满':nextName(state)}</span><button class="text-button" data-panel="requirements">${requirementsExpanded?'收起条件':'突破条件'}</button></div><p class="breakthrough-hint ${ready?'ready':''}">${isBusy(state)?'先完成当前斗法或奇遇':finished(state)?'当前版本境界已圆满':ready?'条件齐备，可立即突破（必定成功）':'还需 '+missing.map(r=>`${short(r.need-r.value)} ${r.label}`).join('、')}</p>${requirementsExpanded?`<div class="requirements">${requirements(state).filter(r=>r.need).map(r=>`<div class="requirement"><span>${r.label}<small>${source[r.label]}</small></span><strong class="${r.value>=r.need?'met':''}">${short(r.value)} / ${short(r.need)}${r.value>=r.need?' ✓':''}</strong></div>`).join('')}<p class="small-note">${majorBreak(state)&&state.realm?'跨大境界消耗修为、灵石、灵髓及破境丹。':'小境界与首次炼气仅消耗修为。'}道悟不消耗。<button class="inline-help" data-help="breakthrough">说明</button></p></div>`:''}</div>`;}

function history(limit){return state.history.slice(0,limit).map(h=>`<div class="history-row ${esc(h.kind)}"><time>第 ${h.day} 日</time><p>${esc(h.text)}</p></div>`).join('');}
function offline(){const r=state.offlineReport;if(!r)return '';return `<section class="offline-card"><div class="activity-line"><strong>离线收益已到账</strong><span>结算 ${duration(r.credited)}</span><button class="quiet" data-action="dismissOffline" aria-label="收起离线收益">×</button></div><p>修为 +${short(r.exp)} · 灵石 +${short(r.stones)} · 灵草 +${short(r.herbs)} · 玄铁 +${short(r.ore)} · 灵髓 +${short(r.shards)}</p>${r.capped?'<small>超过8小时的部分不计收益；修为最多积累至当前上限。</small>':''}</section>`;}

function idlePanel(){const boosted=state.boostUntil>Date.now(),rate=idleRate(state)*(boosted?2:1),wait=Math.max(0,Math.ceil((state.lastMeditate+60000-Date.now())/1000)),full=state.exp>=needExp(state),restWait=Math.max(0,Math.ceil((state.lastRest+60000-Date.now())/1000));return `<section class="cultivation-board">${goal()}<div class="cultivation-scene"><img class="cultivator" src="cultivator.webp" width="150" height="150" alt="青衣修士静坐修行"><div class="cultivation-scene-copy"><p>${finished(state)?'真仙圆满':full?'修为已满，等待突破':'自动修炼中'}</p><strong>${boosted?'聚灵双倍 · ':''}每分钟 +${fmt(rate*60)} 修为</strong>${boosted?`<small>聚灵剩余 ${duration((state.boostUntil-Date.now())/1000)}</small>`:'<small>离线也可修炼 · 最多结算8小时</small>'}</div></div><div class="cultivation-meter"><div><span>修为</span><strong>${fmt(state.exp)} / ${fmt(needExp(state))}</strong></div><div class="bar" role="progressbar" aria-label="当前修为" aria-valuemin="0" aria-valuemax="${needExp(state)}" aria-valuenow="${state.exp}"><i style="width:${percent(state.exp,needExp(state))}%"></i></div></div><div class="training-buttons"><button class="primary" data-action="cultivate" ${state.energy<2||wait||full||finished(state)?'disabled':''}>${wait?`凝神（${wait}秒）`:'凝神修炼'}<small>+${fmt(idleRate(state)*45)} 修为 · 精力-2</small></button><button class="secondary" data-action="rest" ${restWait?'disabled':''}>${restWait?`调息（${restWait}秒）`:'调息恢复'}<small>气血回满 · 精力+4</small></button></div><p class="training-note">${full?'修为满后暂停增长，点上方「突破」继续。':state.energy<2?'精力不足2点；调息恢复，或等待自然恢复。':'凝神、调息每分钟各一次；自动修炼不需要点击。'}</p></section>`;}

function expeditionCard(){const e=state.expedition;if(!e)return `<section class="activity-card expedition-card"><div class="activity-line"><span class="status-label">巡山</span><strong>尚未派遣灵傀</strong><button class="secondary" data-tab="world">去派遣</button></div><p class="small-note">先挑战守关，通关后即可自动巡山。</p></section>`;const sec=expeditionSeconds(state);return `<section class="activity-card expedition-card"><div class="activity-line"><span class="status-label">巡山中</span><strong>${ZONES[e.zone].name}</strong><button class="text-button" data-action="stopExpedition">召回</button></div><div class="bar"><i style="width:${percent(e.progress,sec)}%"></i></div><p class="small-note">本趟还需 ${duration(sec-e.progress)} · 已完成 ${e.rounds} 趟<br>每趟 ${ZONES[e.zone].stones} 灵石 / ${ZONES[e.zone].herbs} 灵草 / ${ZONES[e.zone].ore} 玄铁</p></section>`;}

function jobCard(){if(!state.job)return '';const j=state.job;return `<section class="activity-card job-card"><div class="activity-line"><span class="status-label">炼制中</span><strong>${esc(j.name)}${j.qty>1?' ×'+j.qty:''}</strong><span>${duration(j.remaining)}</span></div><div class="bar"><i style="width:${percent(j.seconds-j.remaining,j.seconds)}%"></i></div><p class="small-note">完成后自动入袋 · 材料已扣除</p></section>`;}

function encounter(){const e=state.encounter;const content={
 spring:{title:'石隙灵泉',tag:'山野奇遇',text:'苔痕深处，一线清泉从石隙流出。泉中灵气充盈，几株碧色灵草正随风轻摇。',choices:[['drink','俯身饮泉','增长修为与道悟，恢复 16 气血'],['gather','采草寻石',`获得 ${3+e.zone} 灵草、${7+e.zone*4} 灵石`]]},
 traveler:{title:'雨中行者',tag:'萍水相逢',text:'古亭下，一名负伤的行者正护着将熄的炉火。见你走近，他笑道：“同是行路人，不妨坐一坐。”',choices:[['help','赠他一株灵草','消耗 1 灵草，获得 1 灵髓、2 道悟'],['talk','坐下听一段往事','获得 2 道悟与修为']]},
 ruin:{title:'无字残碑',tag:'前人遗迹',text:'荒草之间立着半截残碑，斑驳的纹路似乎暗藏心法。碑下有微光闪动，却也残留着一道禁制。',choices:[['study','静观碑纹','获得 3 道悟与修为'],['search','破开旧阵',`获得 1 灵髓、${8+e.zone*6} 灵石，损失 ${5+e.zone*3} 气血`]]},
 beast:{title:ZONES[e.zone].enemy+'拦路',tag:'狭路相逢',text:'林间忽然静了下来。一道身影横在前路，瞳中灵光闪烁。它脚边的石缝里，藏着一枚温润的灵髓。',choices:[['fight','拔剑应战','胜利可得灵髓、灵石与修为'],['leave','收敛气息，绕道而行','安全离开，不获奖励']]},
 herb:{title:'灵草生幽谷',tag:'取舍之间',text:'你在幽谷发现一丛灵草。外围的几株伸手可及，深处却有妖兽盘踞，守着更珍贵的灵髓。',choices:[['gather','见好就收',`安全获得 ${2+e.zone} 灵草、${6+e.zone*4} 灵石`],['guard','深入幽谷','与守护妖兽斗法，胜利获得灵髓']]}
 }[e.id];return `<div class="panel-heading"><h3>${content.title}</h3><span class="tag">${content.tag}</span></div><p class="narrative">${content.text}</p><div class="choice-list">${content.choices.map((c,i)=>`<button class="choice" data-choice="${c[0]}" ${c[0]==='help'&&state.herbs<1?'disabled':''}><span><strong>${c[1]}</strong><small>${c[2]}</small></span><span class="choice-mark">${i?'乙':'甲'}</span></button>`).join('')}</div>`;}
function combat(){const b=state.battle;const charged=b.turn%3===0;return `<div class="combat-head"><h3>${b.name}</h3><span class="round">第 ${b.turn} 回合</span><span class="tag">斗法</span></div><div class="enemy-hp"><div class="stat-line"><span>敌方气血</span><b>${b.hp} / ${b.maxHp}</b></div><div class="bar"><i style="width:${percent(b.hp,b.maxHp)}%"></i></div></div><div class="intent">${charged?'敌方正在蓄势。本回合将重击，可用守势化解。':'敌方剑势平稳。本回合将普通攻击。'}</div><div class="combat-actions"><button class="primary" data-move="attack">挥剑<span class="button-detail">造成 ${attack(state)} 伤害</span></button><button class="primary" data-move="skill" ${b.qi<1?'disabled':''}>御气一剑<span class="button-detail">${attack(state)+8+state.realm*3} 伤害 · 消耗 1 真气</span></button><button class="secondary" data-move="guard">守势<span class="button-detail">减伤 70% · 真气 +1</span></button><button class="secondary" data-move="pill" ${state.pills<1?'disabled':''}>回春丹 ×${state.pills}<span class="button-detail">气血 +${35+state.realm*10} · 敌方仍会反击</span></button></div><div class="combat-footer"><span>真气 ${'◆'.repeat(b.qi)}${'◇'.repeat(2-b.qi)}</span><button class="text-button" data-move="flee">撤离 · 承受一次普攻</button></div><div class="small-note" aria-live="polite">${esc(state.history[0]?.text||'')}</div>`;}
function home(){const active=isBusy(state);return `${saveBlocked?`<div class="busy-note">${esc(saveMessage)}</div>`:''}${active?`<section class="play-panel"><div class="screen-heading"><h2>${state.battle?'正在斗法':'山中奇遇'}</h2><span>${ZONES[state.zone].name}</span></div>${state.battle?combat():encounter()}</section>`:idlePanel()}${functionGrid()}<div class="activity-grid">${expeditionCard()}${jobCard()}</div>${offline()}<section class="recent"><div class="section-header"><h3>仙途记录</h3><button class="text-button" data-tab="journal">全部记录</button></div>${history(2)}</section>`;}

function world(){return `<div class="page-title"><p class="eyebrow">山河卷</p><h2>历练</h2><p>先挑战守关，获胜后开启自动巡山。一次巡一地，切换会放弃当前未完成的一趟。</p></div>${expeditionCard()}${isBusy(state)?`<div class="busy-note">还有一场际遇未结束。<button class="secondary" data-tab="home">回到${state.battle?'斗法':'奇遇'}</button></div>`:''}<div class="zone-list">${ZONES.map((z,i)=>{const locked=state.realm<z.level,cleared=state.cleared[i],foe=enemyStats(i);return `<section class="zone ${locked?'locked':''}"><p class="eyebrow">${cleared?'已通关':locked?'尚未开放':'可挑战'}</p><h3>${z.name}</h3><div class="zone-meta">${locked?`${REALMS[z.level].name}境解锁`:'可挑战'} · 敌方气血 ${foe.hp} / 攻击 ${foe.attack}</div><div class="yield-line">每 ${expeditionSeconds(state,i)} 秒：${z.stones} 灵石 / ${z.herbs} 灵草 / ${z.ore} 玄铁</div><div class="button-row"><button class="secondary" data-challenge="${i}" ${locked||isBusy(state)||state.energy<2||state.hp<10?'disabled':''}>${locked?'境界未解锁':cleared?'再次挑战':'挑战守关'}<span class="button-detail">消耗 2 精力</span></button><button class="primary" data-expedition="${i}" ${!cleared||state.expedition?.zone===i?'disabled':''}>${state.expedition?.zone===i?'正在巡山':cleared?'自动巡山':'通关后巡山'}<span class="button-detail">离线也有收益</span></button></div>${!locked&&(state.energy<2||state.hp<10)?`<p class="blocked-reason">${state.energy<2?'精力不足 2 点。':''}${state.hp<10?'气血不足 10 点。':''}先回修行页调息。</p>`:''}<button class="text-button explore-link" data-explore="${i}" ${locked||isBusy(state)||state.energy<2||state.hp<10?'disabled':''}>随缘探访 · 消耗 2 精力</button></section>`;}).join('')}</div>`;}
function sect(){const current=SECTS.find(x=>x.id===state.sect);return `<div class="page-title"><p class="eyebrow">宗门录</p><h2>${current?current.name:'宗门'}</h2><p>${current?`${current.motto}。每分钟自动获得 1 贡献，功法加成长期保留。`:'炼气境即可拜入宗门。所修功法均可兼习，宗门天赋各有侧重。'}</p></div>${current?`<section class="sect-banner"><div><p class="eyebrow">${rankName(state)}</p><h3>${fmt(state.contribution)} <small>可用贡献</small></h3><p>累计贡献 ${fmt(state.sectEarned)} · ${current.effect}</p></div><span class="sect-seal">${current.name.slice(0,1)}</span></section><section class="activity-card"><div class="section-header"><h3>宗门差事</h3><span class="muted">每分钟一次</span></div><div class="button-row"><button class="secondary" data-errand="herbs" ${state.herbs<5||state.lastErrand+60000>Date.now()||isBusy(state)?'disabled':''}>供奉 5 灵草<span class="button-detail">贡献 +${8+state.realm*2}</span></button><button class="secondary" data-errand="ore" ${state.ore<5||state.lastErrand+60000>Date.now()||isBusy(state)?'disabled':''}>供奉 5 玄铁<span class="button-detail">贡献 +${8+state.realm*2}</span></button></div><p class="small-note">身份随累计贡献提升：100 内门 / 500 亲传 / 2,000 执事 / 8,000 长老。每升一阶，修炼效率额外 +5%。</p></section><div class="section-header"><h3>藏经阁</h3></div><div class="technique-grid">${TECHNIQUES.map(t=>{const cost=techniqueCost(state,t.id),lv=state.techniques[t.id];return `<section class="technique"><div class="section-header"><h3>${t.name}</h3><span class="tag">${lv} / ${t.max} 重</span></div><p>${t.desc}</p><div class="bar"><i style="width:${percent(lv,t.max)}%"></i></div><p class="cost">${lv===t.max?'此法已臻圆满':'消耗 '+costText(cost)}</p>${lv<t.max&&missingCost(cost)?`<p class="blocked-reason">还差 ${missingCost(cost)}。贡献来自宗门差事与每分钟积累。</p>`:''}<button class="secondary" data-learn="${t.id}" ${lv>=t.max||!canAfford(state,cost)||isBusy(state)?'disabled':''}>${lv?'精进一重':'研习此法'}</button></section>`;}).join('')}</div>`:''}<div class="section-header"><h3>${current?'山门来往':'三座山门'}</h3>${current?'<span class="muted">改换需 200 灵石，功法与贡献保留</span>':''}</div><div class="sect-list">${SECTS.map(s=>`<section class="sect-option ${state.sect===s.id?'selected':''}"><div><h3>${s.name}</h3><p>${s.desc}</p><strong>${s.effect}</strong></div><button class="${state.sect===s.id?'secondary':'primary'}" data-sect="${s.id}" ${state.realm<1||state.sect===s.id||isBusy(state)||state.sect&&state.stones<200?'disabled':''}>${state.realm<1?'炼气可入':state.sect===s.id?'当前宗门':state.sect?'改换':'拜入'}</button></section>`).join('')}</div>`;}
function station(id){const cost=stationCost(state,id),lv=state[id];return `<div class="station"><div><p class="eyebrow">${id==='furnace'?'百草归炉':'百炼成器'}</p><h3>${id==='furnace'?'丹炉':'锻炉'} · ${lv} 阶</h3><p>${id==='furnace'?'每升一阶加快炼丹，2 阶解锁聚灵丹':'每阶允许淬炼 3 重法器，最高 30 重'}</p></div><button class="secondary" data-station="${id}" ${lv>=10||!canAfford(state,cost)||isBusy(state)?'disabled':''}>${lv>=10?'已至十阶':'升阶'}<span class="button-detail">${lv>=10?'':'消耗 '+costText(cost)}</span></button>${lv<10&&missingCost(cost)?`<p class="blocked-reason">升阶还差 ${missingCost(cost)}</p>`:''}</div>`;}
function recipeCard(r){const p=craftingPlan(state,r.id);return `<section class="recipe"><div class="section-header"><h3>${r.name}</h3><span class="tag">持有 ${state[r.item]}</span></div><p>${r.description}</p><p class="cost">每枚 ${costText(p.cost)}</p><p class="small-note">${duration(p.seconds)} / 枚 · 需要 ${r.station} 阶丹炉</p>${state.job?'<p class="blocked-reason">当前已有炼制任务，完成后才能再开炉。</p>':state.furnace<r.station?`<p class="blocked-reason">先把丹炉升至 ${r.station} 阶。</p>`:missingCost(p.cost)?`<p class="blocked-reason">还差 ${missingCost(p.cost)}。<button class="inline-help" data-help="resources">材料从哪来？</button></p>`:''}<div class="button-row"><button class="secondary" data-craft="${r.id}" data-qty="1" ${state.job||state.furnace<r.station||!canAfford(state,p.cost)||isBusy(state)?'disabled':''}>炼制 1 枚</button><button class="secondary" data-craft="${r.id}" data-qty="5" ${state.job||state.furnace<r.station||!canAfford(state,craftingPlan(state,r.id,5).cost)||isBusy(state)?'disabled':''}>炼制 5 枚</button></div></section>`;}
function bag(){return `<div class="page-title"><p class="eyebrow">百艺坊</p><h2>百艺</h2><p>一炉同时炼一件事，材料在开炉时扣除。灵傀巡山，为炉火添柴。</p></div>${jobCard()}<div class="art-tabs" role="tablist" aria-label="百艺分类">${[['alchemy','丹房'],['forge','炼器'],['inventory','行囊与坊市']].map(([id,name])=>`<button role="tab" aria-selected="${artTab===id}" class="${artTab===id?'active':''}" data-art-tab="${id}">${name}</button>`).join('')}</div>${artTab==='alchemy'?`${station('furnace')}<div class="recipe-grid">${RECIPES.map(recipeCard).join('')}</div><p class="guidance">跨越炼气之后的大境界，需要破境丹；服用聚灵丹可加快闭关。小境界不消耗丹药。</p>`:artTab==='forge'?`${station('forge')}<div class="recipe-grid">${['weapon','armor'].map(id=>{const p=craftingPlan(state,id);return `<section class="recipe"><div class="section-header"><h3>${id==='weapon'?'佩剑':'法衣'}</h3><span class="tag">${state[id]} / 30 重</span></div><p>${id==='weapon'?`每重攻伐 +6，现有额外 +${state.weapon*6}`:`每重气血 +14、护体 +2`}</p>${p?`<p class="cost">${costText(p.cost)}</p><p class="small-note">${duration(p.seconds)} · 需要 ${p.required} 阶锻炉</p>${state.job?'<p class="blocked-reason">先等当前炼制任务完成。</p>':state.forge<p.required?`<p class="blocked-reason">需要先升级锻炉至 ${p.required} 阶。</p>`:missingCost(p.cost)?`<p class="blocked-reason">还差 ${missingCost(p.cost)}。</p>`:''}<button class="secondary" data-craft="${id}" data-qty="1" ${state.job||state.forge<p.required||!canAfford(state,p.cost)||isBusy(state)?'disabled':''}>淬炼至 ${state[id]+1} 重</button>`:'<p class="gold">此器已臻圆满。</p>'}</section>`;}).join('')}</div>`:inventory()}`;}
function inventory(){return `<div class="inventory-grid">${[['灵草',state.herbs],['玄铁',state.ore],['灵髓',state.shards],['道悟',state.insight],['破境丹',state.breakPills],['灵石',state.stones]].map(([n,v])=>`<div><span>${n}</span><b>${fmt(v)}</b></div>`).join('')}</div><div class="items"><section class="item"><span class="quantity">${state.pills}</span><h3>回春丹</h3><p>恢复 ${35+state.realm*10} 气血。斗法中服用占用一个回合。</p><button class="secondary" data-action="usePill" ${!state.pills||state.hp===maxHp(state)?'disabled':''}>服用</button></section><section class="item"><span class="quantity">${state.spiritPills}</span><h3>聚灵丹</h3><p>自动修炼翻倍 30 分钟。可叠加至 8 小时。</p><button class="secondary" data-action="useSpirit" ${!state.spiritPills?'disabled':''}>服用</button></section></div><div class="section-header"><h3>山下坊市</h3></div><div class="shop">${[['pill','回春丹','回复气血，备不时之需',12],['shard','灵髓','破境与炼制破境丹所需',28],['ore','玄铁 ×5','锻器、升炉、宗门供奉',15]].map(([id,title,desc,cost])=>`<div class="shop-row"><div><h3>${title}</h3><p>${desc}</p></div><button class="secondary" data-buy="${id}" ${state.stones<cost||isBusy(state)?'disabled':''}>${state.stones<cost?`还差 ${cost-state.stones} 灵石`:`${cost} 灵石`}</button></div>`).join('')}</div>`;}
function journal(){return `<div class="page-title"><p class="eyebrow">行路手记</p><h2>仙途记录</h2></div><p class="journal-intro">${esc(state.name)} · ${levelName(state)}<br><small>亲历 ${state.visited} 次 · 斗法获胜 ${state.won} 场 · 灵傀巡山 ${state.expeditionRounds} 趟</small></p><div class="realm-road">${REALMS.map((r,i)=>`<span class="${i===state.realm?'current':i<state.realm?'passed':''}">${r.name}</span>`).join('')}</div><div class="all-journal">${history(80)}</div><p class="small-note">记录最近 80 件经历，新事在前。</p>`;}

function tutorialCard(){const t=state.tutorial;if(t.status!=='active')return '';const g=guideInfo(state);return `<section class="tutorial-card"><div class="tutorial-summary"><button class="tutorial-title" data-guide-expand="toggle"><span>新手 ${g.index+1}/${GUIDE_STEPS.length}</span><strong>${g.title}</strong></button><button class="secondary" data-guide-route="tutorial">${g.done?'已完成':'跟着做'}</button>${g.done?`<button class="primary" data-tutorial="next">${g.index===5?'完成':'下一步'}</button>`:''}<button class="text-button" data-guide-expand="toggle">${guideExpanded?'收起':'展开'}</button></div>${guideExpanded?`<div class="tutorial-body"><p>${g.description}</p><p class="tutorial-status">${g.done?'✓ 这一步你已做到，可直接继续。':g.hint}</p><div class="button-row"><button class="secondary" data-guide-route="tutorial">${g.label}</button><button class="primary" data-tutorial="next" ${g.done?'':'disabled'}>${g.index===5?'完成教程':'下一步'}</button></div><div class="tutorial-foot"><button class="text-button" data-tutorial="previous" ${g.index===0?'disabled':''}>上一步</button><button class="text-button" data-tutorial="skip">跳过这步</button><button class="text-button" data-tutorial="pause">暂时关闭</button></div></div>`:''}</section>`;}

function nextActionCard(){const n=nextTask(state);return `<div class="next-action"><span>指引</span><p>${n.title}</p><button class="text-button" data-guide-route="next">去看看</button></div>`;}

function restoreGuideHighlight(scroll=false){if(!guideTarget)return;let el=null;try{const matches=Array.from(document.querySelectorAll(guideTarget));el=matches.find(x=>x.getClientRects?.().length)||null;}catch{}if(!el)return;el.classList.add('tutorial-target');if(scroll){el.scrollIntoView({behavior:'smooth',block:'center'});if(el.tagName==='BUTTON'&&!el.disabled)el.focus({preventScroll:true});}}
function routeGuide(kind){const g=kind==='tutorial'?guideInfo(state):nextTask(state);tab=g.tab;artTab=g.artTab??artTab;guideTarget=g.target;if(g.target==='.goal')requirementsExpanded=true;render();restoreGuideHighlight(true);}
async function changeTutorial(command){await withSaveLock(()=>{syncFromStorage();tutorialControl(state,command);if(['replay','resume'].includes(command))guideExpanded=true;guideTarget=null;save();render();});if(command==='replay'||command==='resume')window.scrollTo({top:0,behavior:'smooth'});}
function openHelp(section='overview'){$('#help-dialog').showModal();const target=$('#help-'+section);if(target?.scrollIntoView)target.scrollIntoView({block:'start'});}


function functionGrid(){return `<section class="function-panel"><h3>常用功能</h3><div class="function-grid">${[['world','历练','挑战 / 奇遇'],['expedition','巡山','自动收集'],['sect','宗门','拜师 / 贡献'],['techniques','功法','提升实力'],['alchemy','炼丹','制作丹药'],['forge','炼器','强化装备'],['inventory','行囊','查看物品'],['shop','坊市','兑换资源'],['help','教程','玩法说明']].map(([id,label,hint])=>`<button data-shortcut="${id}"><strong>${label}</strong><small>${hint}</small></button>`).join('')}</div></section>`;}
function playerHud(){return `<section class="player-hud"><div class="identity-row"><div class="identity-seal" aria-hidden="true">道</div><div><strong>${esc(state.name)}</strong><span>${state.sect?SECTS.find(x=>x.id===state.sect).name+' · '+rankName(state):'散修'}</span></div><b>${levelName(state)}</b></div><div class="hud-stats"><span>气血 <b>${state.hp}/${maxHp(state)}</b></span><span>精力 <b>${state.energy}/${maxEnergy(state)}</b></span><span>攻伐 <b>${attack(state)}</b></span><span>护体 <b>${armor(state)}</b></span></div><div class="hud-resources">${[['stones','灵石'],['insight','道悟'],['shards','灵髓'],['herbs','灵草'],['ore','玄铁'],['contribution','贡献']].map(([id,name])=>`<button data-help="resources" aria-label="${name} ${fmt(state[id])}，点击查看用途">${name}<b>${short(state[id])}</b></button>`).join('')}</div></section>`;}
function openShortcut(id){if(id==='help'){openHelp();return;}const routes={world:['world',null,null],expedition:['world',null,'.expedition-card'],sect:['sect',null,null],techniques:['sect',null,state.sect?'.technique-grid':'.sect-list'],alchemy:['bag','alchemy',null],forge:['bag','forge',null],inventory:['bag','inventory',null],shop:['bag','inventory','.shop']};const route=routes[id];if(!route)return;tab=route[0];if(route[1])artTab=route[1];guideTarget=route[2];render();if(guideTarget)restoreGuideHighlight(true);else window.scrollTo({top:0,behavior:'instant'});}

function render(){
 const focused=document.activeElement,focusKey=focused?.dataset?.action;
 $('#day').textContent=`仙历第 ${state.day} 日`;
 const main=tab==='home'?home():tab==='world'?world():tab==='sect'?sect():tab==='bag'?bag():journal();
 const guidance=state.tutorial.status==='active'?tutorialCard():tab==='home'?nextActionCard():'';
 $('#app').innerHTML=`${playerHud()}${guidance}<main class="main" id="main-content">${isBusy(state)&&!['home','world'].includes(tab)?`<div class="busy-note">先完成当前${state.battle?'斗法':'奇遇'}，再学习、购买或开炉。<button class="secondary" data-tab="home">返回${state.battle?'斗法':'奇遇'}</button></div>`:''}${main}</main>`;
 document.querySelectorAll('.nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false');});
 restoreGuideHighlight(false);
 if(focusKey){const matches=Array.from(document.querySelectorAll(`[data-action="${focusKey}"]`));const el=matches.find(x=>x.getClientRects?.().length&&!x.disabled);if(el?.focus)el.focus({preventScroll:true});}
}

function switchTab(next){if(!['home','world','sect','bag','journal'].includes(next))return;tab=next;render();window.scrollTo({top:0,behavior:'instant'});}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;if(d.shortcut)openShortcut(d.shortcut);else if(d.guideExpand){guideExpanded=!guideExpanded;render();}else if(d.panel==='requirements'){requirementsExpanded=!requirementsExpanded;render();}else if(d.tutorial)await changeTutorial(d.tutorial);else if(d.guideRoute)routeGuide(d.guideRoute);else if(d.help)openHelp(d.help);else if(d.tab){guideTarget=null;switchTab(d.tab);}else if(d.artTab){artTab=d.artTab;render();}else if(d.action)await resultAction(d.action);else if(d.explore!==undefined||d.challenge!==undefined){const r=await resultAction(d.challenge!==undefined?'challenge':'explore',{zone:Number(d.challenge??d.explore)});if(r.ok)switchTab('home');}else if(d.choice)await resultAction('choice',{choice:d.choice});else if(d.move)await resultAction('combat',{move:d.move});else if(d.buy)await resultAction('buy',{item:d.buy});else if(d.expedition!==undefined)await resultAction('startExpedition',{zone:Number(d.expedition)});else if(d.sect)await resultAction('joinSect',{id:d.sect});else if(d.errand)await resultAction('errand',{id:d.errand});else if(d.learn)await resultAction('learn',{id:d.learn});else if(d.station)await resultAction('upgradeStation',{id:d.station});else if(d.craft)await resultAction('startCraft',{id:d.craft,qty:Number(d.qty)});});
$('.brand').addEventListener('click',e=>{e.preventDefault();switchTab('home');});
$('#help-open').addEventListener('click',()=>openHelp());
$('#tutorial-replay').addEventListener('click',()=>{$('#help-dialog').close();void changeTutorial('replay');});
$('#tutorial-resume').addEventListener('click',()=>{$('#help-dialog').close();void changeTutorial('resume');});
$('#save-open').addEventListener('click',()=>{$('#name-input').value=state.name;$('#reset-confirm').hidden=true;$('#save-dialog').showModal();});
$('#rename').addEventListener('click',async()=>{const name=$('#name-input').value.trim();if(!name){toast('请留下一个道号。');return;}await withSaveLock(()=>{syncFromStorage();state.name=name.slice(0,12);save();render();});toast('道号已记下。');});
$('#reset-open').addEventListener('click',()=>{$('#reset-confirm').hidden=false;});$('#reset-cancel').addEventListener('click',()=>{$('#reset-confirm').hidden=true;});
$('#reset').addEventListener('click',async()=>{await withSaveLock(()=>{state=createState();tab='home';saveBlocked=false;lastRaw=null;save();render();});$('#save-dialog').close();toast('山门仍在，重新出发。');});
$('#save-dialog').addEventListener('click',e=>{if(e.target===$('#save-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});
async function tick(report=false){if(saveBlocked)return;await withSaveLock(()=>{syncFromStorage();applyElapsed(Date.now(),report);save();if(!document.hidden)render();});}
setInterval(()=>{if(!document.hidden)void tick(true);},5000);
document.addEventListener('visibilitychange',()=>void tick(!document.hidden));
window.addEventListener('storage',e=>{if(e.key===KEY){syncFromStorage();render();}});

render();save();if(saveMessage)toast(saveMessage);
const actions=['cultivate','rest','explore','challenge','choice','combat','breakthrough','startExpedition','stopExpedition','joinSect','errand','learn','upgradeStation','startCraft','buy','usePill','useSpirit'];
const context=document.modelContext;if(context?.registerTool){const lifetime=new AbortController();window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});const register=t=>{try{Promise.resolve(context.registerTool(t,{signal:lifetime.signal})).catch(()=>{});}catch{}};
 register({name:'read_cultivation_state',description:'Read the current local cultivation progress, resources, sect, expedition and crafting job without changing the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>({name:state.name,realm:levelName(state),hp:state.hp,energy:state.energy,stones:state.stones,ore:state.ore,herbs:state.herbs,sect:state.sect,techniques:state.techniques,requirements:requirements(state),expedition:state.expedition,job:state.job,encounter:state.encounter,battle:state.battle})});
 register({name:'take_cultivation_action',description:'Perform one visible game action and save resulting progress in this browser. Does not reset or rename a character.',inputSchema:{type:'object',properties:{action:{type:'string',enum:actions},zone:{type:'integer',minimum:0,maximum:6},choice:{type:'string'},move:{type:'string'},item:{type:'string'},id:{type:'string'},qty:{type:'integer',enum:[1,5]}},required:['action'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!input||typeof input!=='object'||!actions.includes(input.action))throw new Error('无效的游戏行动');const r=await resultAction(input.action,input);return {...r,realm:levelName(state),hp:state.hp,energy:state.energy,localSave:saved};}});
}
