import {VERSION,validateSave,pauseTowerRun} from './scroll-engine.js?v=5.1.1';
export const KEY='wenshan-scroll-v3',LEGACY_KEY='wenshan-save-v1';
let trustedRaw=null,trustedVersion=null;
export function readSave(storage,knownRaw){const raw=storage.getItem(KEY),recoveryPending=!!storage.getItem(KEY+'-restore-pending');if(knownRaw!==undefined&&raw===knownRaw&&!recoveryPending)return {unchanged:true,raw};try{const parsed=JSON.parse(raw),s=validateSave(parsed);if(s){trustedRaw=raw;trustedVersion=parsed.version;return {state:s,raw,blocked:recoveryPending,recoveryPending,migrated:parsed.equipment?.head===undefined,migratedItems:parsed.gearInstances===undefined,migratedTreasures:parsed.activatedTreasures===undefined||parsed.equipment?.charm!==s.equipment.charm,migratedTower:parsed.version<9,migratedCore:parsed.version<8,migratedSpecialization:parsed.version<7,migratedFieldTrials:parsed.version<6,migratedResonance:parsed.version<5,migratedFoundation:parsed.version===3||!!parsed.ascended&&parsed.level===10};}}catch{}try{const backup=storage.getItem(KEY+'-last-good'),parsed=JSON.parse(backup),s=validateSave(parsed);if(s){trustedRaw=backup;trustedVersion=parsed.version;return {state:s,raw:backup,blocked:recoveryPending,recoveryPending,recovered:true,migratedTreasures:parsed.activatedTreasures===undefined||parsed.equipment?.charm!==s.equipment.charm,migratedTower:parsed.version<9,migratedCore:parsed.version<8,migratedSpecialization:parsed.version<7,migratedFieldTrials:parsed.version<6,migratedResonance:parsed.version<5,migratedFoundation:parsed.version===3||!!parsed.ascended&&parsed.level===10};}}catch{}return {state:null,raw,blocked:!!raw||recoveryPending,recoveryPending};}
export function preserveLegacy(storage){const raw=storage.getItem(LEGACY_KEY);if(raw&&!storage.getItem(LEGACY_KEY+'-before-scroll'))storage.setItem(LEGACY_KEY+'-before-scroll',raw);return !!raw;}
export function writeSave(storage,state,previous){const revision=state.revision+1,savedAt=Date.now(),raw=JSON.stringify({...state,version:VERSION,revision,savedAt});let previousVersion=previous===trustedRaw?trustedVersion:null,validPrevious=previous===trustedRaw;if(previous&&(!validPrevious||previousVersion===null)){try{const parsed=JSON.parse(previous);validPrevious=!!validateSave(parsed);previousVersion=parsed?.version;}catch{}}const enteringCurrent=!validPrevious||previousVersion<VERSION;if(enteringCurrent){let legacy=validPrevious&&previousVersion<VERSION?previous:null;if(!legacy){try{const current=storage.getItem(KEY),parsed=JSON.parse(current);if(parsed?.version<VERSION&&validateSave(parsed))legacy=current;}catch{}}if(legacy){if(!storage.getItem(KEY+'-before-auto-tower'))storage.setItem(KEY+'-before-auto-tower',legacy);if(JSON.parse(legacy).version<8&&!storage.getItem(KEY+'-before-golden-core'))storage.setItem(KEY+'-before-golden-core',legacy);if(JSON.parse(legacy).version<7&&!storage.getItem(KEY+'-before-sect-crafting'))storage.setItem(KEY+'-before-sect-crafting',legacy);if(JSON.parse(legacy).version<6&&!storage.getItem(KEY+'-before-field-trials'))storage.setItem(KEY+'-before-field-trials',legacy);if(JSON.parse(legacy).version<5&&!storage.getItem(KEY+'-before-resonance'))storage.setItem(KEY+'-before-resonance',legacy);if(JSON.parse(legacy).version===3&&!storage.getItem(KEY+'-before-foundation-chapter'))storage.setItem(KEY+'-before-foundation-chapter',legacy);}storage.setItem(KEY+'-last-good',raw);}else if(previous&&validPrevious){try{storage.setItem(KEY+'-last-good',previous);}catch(error){let compatible=false;try{const backup=JSON.parse(storage.getItem(KEY+'-last-good'));compatible=backup?.version>=VERSION&&!!validateSave(backup);}catch{}if(!compatible)throw error;}}storage.setItem(KEY,raw);state.version=VERSION;state.revision=revision;state.savedAt=savedAt;trustedRaw=raw;trustedVersion=VERSION;return raw;}


// The pending marker freezes recovery copies across reloads/retries until both live slots are safe.
const PENDING=KEY+'-restore-pending';
function clearPending(storage){if(typeof storage.removeItem==='function')storage.removeItem(PENDING);else storage.setItem(PENDING,'');}
export function swapAdventure(storage,rescueRaw=null){let current,previous,valid,keep;try{if(storage.getItem(PENDING))return {ok:false,reason:'pending'};current=storage.getItem(KEY);previous=storage.getItem(KEY+'-previous-adventure');try{valid=validateSave(JSON.parse(previous));}catch{}if(!valid)return {ok:false,reason:'invalid'};keep=current;if(rescueRaw){try{if(validateSave(JSON.parse(rescueRaw)))keep=rescueRaw;}catch{}}if(keep)storage.setItem(KEY+'-before-restore-memory',keep);if(current)storage.setItem(KEY+'-before-restore-current',current);storage.setItem(KEY+'-before-restore-previous',previous);storage.setItem(PENDING,JSON.stringify({createdAt:Date.now()}));}catch{return {ok:false,reason:'storage'};}try{pauseTowerRun(valid,'恢复后已暂停，点击继续');const written=writeSave(storage,valid,previous);if(keep)storage.setItem(KEY+'-previous-adventure',keep);clearPending(storage);trustedRaw=written;trustedVersion=VERSION;return {ok:true,state:valid,raw:written};}catch{try{if(current)storage.setItem(KEY,current);else storage.removeItem?.(KEY);}catch{}try{storage.setItem(KEY+'-previous-adventure',previous);}catch{}return {ok:false,reason:'storage'};}}
export function recoverAdventure(storage,which='current'){try{if(!storage.getItem(PENDING))return {ok:false,reason:'none'};const current=storage.getItem(KEY+'-before-restore-memory')||storage.getItem(KEY+'-before-restore-current'),previous=storage.getItem(KEY+'-before-restore-previous');let a,b;try{a=validateSave(JSON.parse(current));}catch{}try{b=validateSave(JSON.parse(previous));}catch{}const chosen=which==='previous'?b:a;if(!chosen)return {ok:false,reason:'invalid'};const raw=which==='previous'?previous:current,other=which==='previous'?current:previous;pauseTowerRun(chosen,'恢复后已暂停，点击继续');const written=writeSave(storage,chosen,raw);if(other)storage.setItem(KEY+'-previous-adventure',other);clearPending(storage);trustedRaw=written;trustedVersion=VERSION;return {ok:true,state:chosen,raw:written};}catch{return {ok:false,reason:'storage'};}}
